### ISSUE TITLE
[EPIC] - Horizontal Auth(n | z) Project

### ISSUE THREAD

**Issue by samiatoui** [PHACDataHub/DSCO-projects#24]
### 👱 Business Client

n/a

### 🎯 Milestone

M7 - Implementation of an identity-based (Zero-Trust) security model

### 🟢 Start Date (expected)

2023-02-13

### 📋 Detailed Description

Establishing Authentication and Authorization requirements and infrastructure for Zero Trust.

### ⚒️ Tangible Outcomes

Increase security for PHAC systems/data to ensure that PH officials only have access to elements/data needed to perform their required job functions.

Alignment with US/CDC security direction

### 👨‍💻 Intangible Uutcomes

Documented Requirements for Authentication/Authorization for ZTA 
Evaluation of GC authentication options relative to ZT requirements.
Establish working example/PoC of 
Expand PHAC usage/capacity with Zero Trust architecture

### ✔️ Feature List

- [ ]  Identify the authentication and authorization needs for a Zero Trust Archtecture.
- [ ]  Identify points of interaction/integration/conflict with the larger federated model that PHAC is pursuing
- [ ]  Evaluate existing GC solutions (SignInCanada and others), and Ory Keto/Keycloak to determine fit
