### ISSUE TITLE
[EPIC] - Project Name Application

### ISSUE THREAD

**Issue by samiatoui** [PHACDataHub/DSCO-projects#39]
### 👱 Business Client

Sami, Keith

### 🎯 Milestone

M4 - Develop a Cloud Adoption Framework

### 🟢 Start Date (expected)

01-03-2023

### 📋 Detailed Description

A form/application that allows a user to input their project name and receive a formatted project and folder name based on our naming conventions. 

### ⚒️ Tangible Outcomes

Each project will have a unique identifier which makes projects easy to identify and track

### 👨‍💻 Intangible Uutcomes

Allows us to have conventionalized project names.

### ✔️ Feature List

- [ ] [FEAT] - Documentation for the application
- [ ] [FEAT] - Name generator
- [ ] [FEAT] - Name validation
- [ ] [FEAT] - Deploy to Google Cloud Platform (GCP)
