### ISSUE TITLE
[EPIC] - CFEZID-OMD GCP

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/DSCO-projects#49]
### 👱 Business Client

CFEZID-OMD

### 🎯 Milestone

M6 - Define a technology engagement framework

### 🟢 Start Date (expected)

31-03-2023

### 📋 Detailed Description

The CFEZID-OMD team would like to have a GCP Sandbox space to test and play around with their stack and check deployment, CI/CD, and other potential pipelines. They would also ideally like a database service such as a PostgreSQL PaaS on GCP.

### ⚒️ Tangible Outcomes

A GCP project space
A Container that holds their stack
A URL to hit their app on GCP
A database PaaS
Automatic Infra deployment through code/script

### 👨‍💻 Intangible Uutcomes

Engagement with Data Integration
GCP knowledge, learning, and training
Potential future stack benefits, downfalls, and use cases

### ✔️ Feature List

- [ ] [FEAT] - A GCP project space
- [ ] [FEAT] - A Container that holds their stack
- [ ] [FEAT] - A URL to hit their app on GCP
- [ ] [FEAT] - A database PaaS
- [ ] [FEAT] - Automatic Infra deployment through code/script

**Comment by Mexmorize** [comment]
You can find more information on this Azure DevOps work item (where Data Integration is tracking the work):

https://dev.azure.com/HCPHAC/National%20Surveillance%20Project/_workitems/edit/4153
