### ISSUE TITLE
[EPIC] - Git for the Pan Canadian Health Inequalities Monitoring

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/DSCO-projects#50]
### 👱 Business Client

Pan Canadian Health Inequalities

### 🎯 Milestone

M1 - Establish a governance Secretariat

### 🟢 Start Date (expected)

31-03-2023

### 📋 Detailed Description

The Pan Canadian Health Inequalities team is looking to get a Git space for their work and version controls. They are currently storing scripts, code, and other things within a SharePoint folder online, which is not meeting their needs, and they're looking to upgrade to a Git system (GitLab, GitHub). 

Their end goal is to have a private space (preferably behind VPN, but not currently required) to learn Git and test functionality to see how it could help with their process/pipelines.

They are quite new to Git, willing to learn, and asking for a point-of-contact for any Git questions they might have.

During the kick-off meeting, there were two potential solutions, GitHub and GCcode.

### ⚒️ Tangible Outcomes

Some basic Git documentation
A GitHub repo/space available
A Routine Training session

### 👨‍💻 Intangible Uutcomes

Building a connection with an external client
Getting some more people within GitHub to promote Open Government
Learning what questions basic users will ask and getting a path forward for new teams

### ✔️ Feature List

- [ ] [FEAT] - Some basic Git documentation
- [ ] [FEAT] - A GitHub repo/space available
- [ ] [FEAT] - A Routine Training session
