### ISSUE TITLE
[EPIC] - Data Discovery Data Needs

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/DSCO-projects#59]
### 👱 Business Client

Data Discovery

### 🎯 Milestone

M4 - Develop a Cloud Adoption Framework

### 🟢 Start Date (expected)

15-03-2023

### 📋 Detailed Description

The Data Discovery Team is looking to upgrade some of its processes and turned to use to collaboratively work on some solutions to problems that are becoming more apparent.

There are a few different things that they wanted to work on to improve, ranging from Data Analysis capabilities within the cloud (GCP), having a GitHub space for their work for version control, their own team website, and others.

### ⚒️ Tangible Outcomes

A GitHub space/repo for their team to sandbox git capabilities
A GCP project for their team to sandbox cloud capabilities
A Website for their team to showcase work they're working on

### 👨‍💻 Intangible Uutcomes

An engagement/communication avenue to an external client (Data Discovery)
A way to onboard a new team into GCP
Learn more about Vertex AI
Learn more about Jupyter Notebooks
Offering different website options for a 'team work showcase'

### ✔️ Feature List

- [ ] [FEAT] - A GitHub space/repo for their team to sandbox git capabilities
- [ ] [FEAT] - A GCP project for their team to sandbox cloud capabilities
- [ ] [FEAT] - A Website for their team to showcase work they're working on
