### ISSUE TITLE
Creating Enterprise-level geolocational services for in-house use as a start-point in an analytical journey.

### ISSUE THREAD

**Issue by NickZachary** [PHACDataHub/DSCO-projects#79]
### 👱 Business Client

Nick, Zachary

### 🎯 Milestone

M2 - Develop Strategic Plan

### 🟢 Start Date (expected)

27-04-2023

### 📋 Detailed Description

Create in-house, hosted Enterprise-level geolocational services exposed through modern APIs for use in analytical processes and workflows which would leverage trust/official point-level address data and NLP techniques to deal with less-than-pristine structured input. 

The exploratory phase will do a precursory environmental scan of available technologies: OpenSource, proprietary, and fee-based resulting in an evaluation based on a weighted score based on criteria specific to PHAC and the GoC needs/limitations.

The second phase will continue to create in-house working prototypes using authoritative point address data, allowing for benchmarking on positional accuracy; processing speed; feedback; ability to track provenance via completed metadata; etc.

The third phase will entail monitoring typical PHAC analyst interaction with any exposed services (i.e. WebAPIs) to see if there are any refinements need to the process, default settings, underlying data, etc.

The fourth phase will incorporate rural township REGEX and fuzzy matching to detect, parse, and return centroid X/Y for QSTRM-like addresses to increase regional coverage and uses with non-traditional urban civic addresses.

### ⚒️ Tangible Outcomes

- providing a well documented API that allows PHAC to develop in-house workflows or applications to submit bulk requests to resolve civic addresses into a spatially accurate and precise  latitude/longitude.
- the ability to track and account for master data provenance to ensure that results can be duplicated and full-transparency by default in the even of ATIP or Proactive Disclosure requests. 
- empowering analysts with geolocational services based on authoritative spatial point data sources to unlock trapped locational data in typical files which can be used a starting point and input parameter in a chain of other analytical processes such as routing.
- leveraging NLP components in geocoding engines which will eliminate or reduce the amount of data cleansing needed or beyond the typical practitioner's wherewithal in scripting.

### 👨‍💻 Intangible Uutcomes

- 

### ✔️ Feature List

- [ ]  [FEAT] - <ability to turn-off any Out-of-the-Box services that automatically populate spatial data from external sources>
- [ ]  [FEAT] - <ability to provide custom point-level address data after reviewing/vetting the source>
- [ ]  [FEAT] - <ability to provide the end user with the provenance and technique used in each address resolution submission>
- [ ]  [FEAT] - <use of NLP and/or REGEX/SOUNDEX for resolving input data which is "dirty">
- [ ]  [FEAT] - <ability to regionally identify civic addresses and use appropriate linguistic business rules>

**Comment by NickZachary** [comment]
![geocoding](https://user-images.githubusercontent.com/131886315/234607790-9d66abfc-8d20-44bf-8891-1d7ff1efe306.jpg)
