### ISSUE TITLE
[EPIC] - Enterprise-level Spatial Routing Services

### ISSUE THREAD

**Issue by NickZachary** [PHACDataHub/DSCO-projects#82]
### 👱 Business Client

Nick, Zachary

### 🎯 Milestone

M2 - Develop Strategic Plan

### 🟢 Start Date (expected)

27-04-2023

### 📋 Detailed Description

Researching, evaluating various FOSS, proprietary, and service-based routing service options to be implemented and available in-house for PHAC analysts to leverage as part of their analytical workflow for spatial-based problems or components.

Specifically, Phase I will entail an environmental scan of the available technologies. These technologies will have hard- and soft-criteria that will be assigned weights based on interviews with end-users as well as based on expert user input. 

Phase II will setup testing environments where the technologies ranked and included in a short-list will be compared, performance rated and benchmarked as well as spatial accuracy statements will be provided.

### ⚒️ Tangible Outcomes

- a comprehensive environmental scan of all technologies available using routing engines will be provided and rated according to an internal critera
-  benchmarking and reporting on the results.
-  building network layers that take into account distance and time impedances 
-  the ability to have live-data or sensor data contribute to temporal aspects of traffic and congestion
-  various routing-based problems can be solved: shortest-time; shortest-distance; isochrone drive-time generation; vehicle-routing optimization prescriptive analytics; matrix generation between destination points; multi-modal travel network based on GTFS
- ability to control the input data and limit it to authoritative sources from M-P-T.
- respecting data governance principles such as use of master and reference data, complete metadata completion and availability in order to be able to duplicate results and encourage transparency of processes.
- services available in a well-documented REST API endpoint to encourage internal users to integrate to whichever workflow and technologies.
- ability to control costs by side-stepping per request costs that some solutions entail (i.e. Google location services).

### 👨‍💻 Intangible Uutcomes

- increase uptake in the DS and non-technical PHAC realms.

### ✔️ Feature List

- [ ] [FEAT] - ability to turn off Third-party data streams
- [ ] [FEAT] - ability to provide own vetted authoritative road and transportation spatial data.
- [ ] [FEAT] - ability to generate shortest-time impedance route generation
- [ ] [FEAT] - ability to generate shortest-distance impedance route generation
- [ ] [FEAT] - ability to generate user-defined incremental drive-time isochrones
- [ ] [FEAT] - ability to provide vehicle routing problem solving / optimization services
- [ ] [FEAT] - ability to provide metadata feedback incorporated in the returned results to verify source, vintage, methods, etc.
