### ISSUE TITLE
[EPIC] - Automated Data Integration with StatCan products

### ISSUE THREAD

**Issue by NickZachary** [PHACDataHub/DSCO-projects#83]
### 👱 Business Client

Nick, Zachary

### 🎯 Milestone

M2 - Develop Strategic Plan

### 🟢 Start Date (expected)

27-04-2023

### 📋 Detailed Description

Given the vast amount of socio-economic data that StatCan holds in individual, longitudinal, and ad hoc / custom surveys - timely, accurate, and automated access to this data would provide better and finer granularity in analysis at a sub-neighborhood level / city level through its synthesis with PHAC-related products and areas of interest.

Notably, StatCan has public-facing Web APIs available in accessing a variety of CANSIM tables that are stored in CODR. Furthermore, asides from the Web Developer Service (WDS) and table downloads (ie., .csv, .tsv, .ivt) StatCan recently adopted SDMX - an international standard employed globally by national statistical organizations (NSOs) which can be accessed programmatically. 

Furthermore, given StatCan follows good data governance policies, the organization's use of reference data through a primary key which transcends time/space (i.e. DGUID) opens the potential for PHAC to transform the returned data into a format that is spatially-suitable for anchoring to common reporting boundaries used Government of Canada (GoC) wide which will enable uniform reporting at various geographic levels.

To start, the 2021 Census is available and a script has been developed to transform and amalgamate each regional/provincial Census file at the Dissemination Area (DA) level, joined to its proper and authoritative spatial infrastructure boundary file -suitable for use in desktop GIS analysis; automated scripting workflows; and WebGIS front ends.

### ⚒️ Tangible Outcomes

- provide an automated method of polling topics of interest to PHAC and efficiently transfer them into the organization for storage and/or immediate use with other products.
- have a constant and trusted connection to authoritative master data via modern Web APIs which can be used in multiple PHAC projects, products, or workflows.
- provide PHAC analysts with the ability to use in-house developed areas of interest or analysis masks with spatially-anchored StatCan products.
- work with StatCan to develop custom reporting geographies which are collected but have yet to be developed.
- create an all-encompassing geographic boundary file which contains many geographic levels and vintages (ie. via DGUID) allowing for 1:M joins to visualize or analyze data with a spatio-tempo component.

### 👨‍💻 Intangible Uutcomes

- increased contact and relationship building with partner agencies (i.e. StatCan)
- increased understanding in navigating, using, and interpreting StatCan data

### ✔️ Feature List

- [ ] [FEAT] - create automation script to poll for changes in StatCan holdings of interest (via WDS, SDMX)
- [ ] [FEAT] - create automation script to pull and transform reponse from StatCan public-facing WebAPI into various formats, especially suited for joining on primary reference keys for reporting geographic boundaries
- [ ] [FEAT] - test, create, and deploy a Web-based front-end with modern UX/UI that promote its use in navigating, sorting, sub-setting, and returning a json repose which can be flattened and joined-on-the-fly to master spatial boundaries which can then be immediately visualized, downloaded locally, and/or used as part of an analytical workflow component.

**Comment by NickZachary** [comment]
![Census_PHAC_v6](https://user-images.githubusercontent.com/131886315/234654092-4bd8d051-ddbb-405e-bab5-134337cb1b4c.jpg)

**Comment by NickZachary** [comment]
[Census_PHAC_v6.zip](https://github.com/PHACDataHub/DSCO-projects/files/11335940/Census_PHAC_v6.zip)

**Comment by NickZachary** [comment]
> [Census_PHAC_v6.zip](https://github.com/PHACDataHub/DSCO-projects/files/11335940/Census_PHAC_v6.zip)

The Draw.Io file for editing the diagram
