### ISSUE TITLE
[EPIC] - Creating and Publishing Spatial Web Processing Services (WPS)

### ISSUE THREAD

**Issue by NickZachary** [PHACDataHub/DSCO-projects#84]
### 👱 Business Client

Nick, Zachary

### 🎯 Milestone

M2 - Develop Strategic Plan

### 🟢 Start Date (expected)

28-04-2023

### 📋 Detailed Description

**SUMMARY**
_Duplicating simple to highly complex spatial analytical workflows as models requires esoteric knowledge and technical wherewithal as well as specialized desktop GIS software and licences. Conceptualizing workflows common to internal PHAC SMEs which black-box geospatial algorithms published and accessible as Web Processing Services (WPS), only necessitating 1+ inputs as well as providing parameters – ensures duplicability of results; uniformity of underlying reference and master data; and  abstraction/modelling targeting a non-technical user-base._

**CURRENT STATE/INCUMBENT**
No known WPS solutions exist within PHAC, therefore any introduction of solutions would constitute as an incumbent for subsequent iterations.

**PERSONAS**
A.	PHAC internal SMEs (e.g. EPIs);
B.	PHAC internal technical audiences (e.g. Data Scientists); and
C.	PHAC internal management  and upper-level executives.

**PAIN POINTS**

- Persona C: “My technical knowledge and currency expired years ago as I moved up the ranks. Generally, I know what I want to do with the data, but due to skill atrophy, I have no way of making this happen without bothering some of the more junior, hands-on members of the team who are already tasked.”
- 
- Persona B: “It is important that we all are singing from the same songbook so we can compare answers. Being scientifically-orientated, fellow Data Scientists and Engineers value data governance principles of reproducibility of results; being able to trace back and identify data sources through completed metadata; as well as being able to “see” inside the blackbox of the algorithm for critique, confirmation, and to provide potential improvements to the WPS down the road.”
- 
- Persona A: “My manager says there is a one in ten chance I will get approved for GIS software since it is expensive to procure and license as well as no having a priority in accessing it, so I depend on other internal PHAC resources as well as being at the mercy of their availability. I would really more timely results and autonomy in being able to carry out my investigation to support my research despite not having the GIS-skills per-se.”

### ⚒️ Tangible Outcomes

- researching, evaluating, and testing WPS solutions against weighted criteria aligning with alleviating or addressing persona pain-points.
- developing, testing, and executing common 80% spatial analytical workflow solutions for internal PHAC users and customizing functionality from the templates.
-  providing public-facing access of published WPS that allow non-technical audiences the ability to provide spatial- and non-spatial inputs (i.e. boundary masking of events as .kml, .shp or on-screen digitizing) along with access to adjusting input parameters  resulting in an analytical output product that is rendered on the screen and downloadable for future use.

### 👨‍💻 Intangible Uutcomes

- developing internal expertise in setting up WPS
- increased contact and understanding of common workflow patterns shared by internal PHAC analysts

### ✔️ Feature List

- [ ] [FEAT] - ability to be executed from Web page interfaces with minimal dependencies on JS libraries.
- [ ] [FEAT] - ability to navigate and upload custom geographic boundaries to act as analytical Areas of Interest or Exclusion Masks
- [ ] [FEAT] - ability to visualize all input parameters prior to execution allowing for adjustments and confirmation
- [ ] [FEAT] - user can easily and intuitively adjust input expected input parameters which have logical default value pre-programmed
- [ ] [FEAT] - complete metadata and documentation for reproducing and confirming published algorithms
- [ ] [FEAT] - on-screen visualization of output
- [ ] [FEAT] - choice in download file formats
- [ ] [FEAT] - well documented REST endpoints available

**Comment by NickZachary** [comment]
![image](https://user-images.githubusercontent.com/131886315/234974535-955b1b89-0d66-4112-ab2e-1ca827cc4bf3.png)

**Comment by NickZachary** [comment]
![image](https://user-images.githubusercontent.com/131886315/234974679-e2c0aa2d-8f61-4129-99db-443eb6f5f0b3.png)

**Comment by NickZachary** [comment]
CLIP

![image](https://user-images.githubusercontent.com/131886315/234975090-fc8c71ca-0ec7-420b-b8c4-e73aac885952.png)

**Comment by NickZachary** [comment]
WITHIN

![image](https://user-images.githubusercontent.com/131886315/234975257-115448db-6a09-4a63-bfc9-fd2155b49f35.png)

**Comment by NickZachary** [comment]
TOUCHES

![image](https://user-images.githubusercontent.com/131886315/234975351-38d17570-b9fe-4f81-be48-26529621d7f7.png)

**Comment by NickZachary** [comment]
CONVEX HULL

![image](https://user-images.githubusercontent.com/131886315/234975578-e4e51dc8-7a49-482a-91be-0a3375100886.png)
