### ISSUE TITLE
[EPIC] - HPOC Modernization

### ISSUE THREAD

**Issue by NickZachary** [PHACDataHub/DSCO-projects#87]
### 👱 Business Client

Durand, Seb

### 🎯 Milestone

M2 - Develop Strategic Plan

### 🟢 Start Date (expected)

19-05-23

### 🔴 End Date (expected)

19-05-2024

### 📋 Detailed Description

Provide technical support to on-going HPOC daily operations and strategic goals. Specifically, provide a Common Operating Picture (COP) dashboard that is geo-centric from multiple operational data sources, enabling decision-makers and senior management visualize, interact, and provide rudimentary "on the ground" analysis of unfolding situations. 

### ⚒️ Tangible Outcomes

- perform a comprehensive environmental scan of available technologies able to support the implementation of a CoP.
- carry out an objective options analysis in choosing the most appropriate piece(s) of technology used to support a CoP through a weighted criteria that reflects factors that respects fiscal stewardship; technological debt; ubiquitous human resources and skills to implement and maintain; performance; interoperability; accessibility; and multilingual support.
- research, enumerate, assess, automate collection of supporting socio-economic, infrastructure, EM-related, and common reporting boundary spatial datasets with emphasis on ensuring sound data governance principles are respected from the get-go (i.e. complete ISO compliant metadata, etc.).
- provide and encapsulate commonly requested summary statistical functions within the CoP for immediate reporting.
- research, brainstorm, test, and implement CoP solutions that immediately comply w/ TB's WGAC 2.0 "AA", looking to the future of WGAC 3.0 standards as well as the intermediate and less-forgiving WGAC 2.3 standards.
- prototype different spatial service deployment, minimizing the need to maintain multiple products based on EN/FR in order to comply w/ any OLA requirements for internally- and externally-facing products. 
- engage with Policy and/or Legal to explore the ramifications of employing Accessibility exemptions for dynamic media types such as WebGIS maps through offering the underlying data as a downloadable table.
- create a HPOC Modernization chatroom in MS Teams and invite designated members.
- elicit user requirements from actual end-users of the CoP through interviews and discussions, consolidating requests by persona - resulting in a "shopping list" of potential features to be evaluated whether they can be included or not.

### 👨‍💻 Intangible Uutcomes

- increase interoperability in workflows, data schemas, standards implemented between Government Operations Centre (GOC) and PHAC.
- increase uptake of senior management and decision makers in confidently employing CoPs as standard operating procedure and culture change
-  decrease the dependency on highly-technical SME resources, democratizing access and interpretation of complex data sources
-  leverage all resources at hand such as SSC and Google, tapping into their corporate knowledge and human capital to provide strategic guidance and tactical wherewithal.
- capitalize on certain project membership in the Federal Collaboration Working Group (FCWG) to ensure maximum interoperability and information exchange.

### ✔️ Feature List

- [ ] [FEAT] - As a decision maker with limited technical skills, I want to toggle  on- and off different operational / intelligence overlays.
- [ ] [FEAT] - As a decision maker, I want multiple data feeds, both near-real time and static, from different official sources represented geospatially in the CoP
- [ ] [FEAT] - As an internal analyst, I want the ability to select different base maps that will give varying contextual information such as hybrid raster map services.
- [ ] [FEAT] - As an internal technical resource supporting the CoP, I want to ensure that common spatial standards are employed and easily ingestible as REST endpoint services to reduce the level of effort needed and onus on curating data.
- [ ] [FEAT] - As an internal analyst, I want the ability to "bring your own data" to the CoP, uploading it in session as an interactive item or analytical mask in the table of contents.
